dist: trusty

language: python

python:
  - "3.5"
  - "3.6"

before_script:
  # install code coverage modules
  - pip3 install codecov
  - pip3 install coverage
  # install the module
  - pip3 install .

script:
  # run tests
  - coverage run -m unittest discover -p "test_*py" upfp

after_script:
  - codecov
